name: Build Docker Image
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need to create an environment variable in lowercase
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.*
          check-latest: true
      # 🤓 https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          path: main
      # 🤓 https://github.com/marketplace/actions/ghcr-docker-buildx-build
      #- name: GHCR Docker Buildx Build
      #  uses: bskiefer/docker_buildx@v1.4
      
      # 🤓 https://github.com/marketplace/actions/ghcr-action
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Build Docker Image0
      #  run: |
      #    docker build -t .  
      #- name: Push Docker Image
      #  run: |
      #    echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      #    docker push ghcr.io/$REPO:$GITHUB_RUN_ID

