name: Build Docker Image
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need to create an environment variable in lowercase
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.*
          check-latest: true
      - name: Build Docker Image
        run: |
          docker build -t $REPO:$GITHUB_RUN_ID . 
      - name: Push Docker Image
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker push ghcr.io/$REPO:$GITHUB_RUN_ID

