name: Build Docker Image
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.*
        check-latest: true
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/habitatenergy/ipsec_exporter:${{ env.GITHUB_SHA }} .
    - name: Push Docker Image
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
        docker push ghcr.io/habitatenergy/ipsec_exporter:${{ env.GITHUB_SHA }}

